# Generated by Django 2.1.7 on 2019-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Prod_id', models.IntegerField()),
                ('c_Prod_title', models.CharField(max_length=100)),
                ('c_Prod_mail', models.EmailField(max_length=254)),
                ('cno', models.IntegerField(default=1)),
                ('ccost', models.IntegerField(default=0)),
                ('cstat', models.CharField(default='no', max_length=3)),
                ('cdeli', models.CharField(default='no', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
                ('cate_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prodcomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_title', models.CharField(max_length=100)),
                ('Prod_umail', models.EmailField(blank=True, max_length=254, null=True)),
                ('Prod_com', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_title', models.CharField(max_length=100)),
                ('Prod_pmail', models.EmailField(max_length=254)),
                ('Prod_model_no', models.CharField(max_length=10)),
                ('Prod_manufacture', models.CharField(max_length=20)),
                ('Prod_weight', models.CharField(max_length=20)),
                ('Prod_no_of_items', models.IntegerField()),
                ('Prod_price', models.IntegerField()),
                ('Prod_description', models.TextField()),
                ('Prod_year', models.CharField(max_length=4)),
                ('Prod_image', models.ImageField(blank=True, upload_to='')),
                ('Prod_genre', models.TextField(max_length=50)),
                ('Prod_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumail', models.CharField(max_length=30)),
                ('rtitle', models.CharField(max_length=100)),
                ('rval', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ureg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufname', models.CharField(max_length=20)),
                ('usname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('umail', models.EmailField(max_length=254)),
                ('upass', models.CharField(max_length=20)),
                ('uphone', models.CharField(max_length=10)),
                ('uaddr', models.TextField()),
                ('', models.CharField(max_length=12)),
                ('utype', models.CharField(default='costumer', max_length=10)),
            ],
        ),
    ]
